name: romoogoola
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.5
  barcode_scan: ^3.0.0
  qr_flutter: ^3.2.0
  firebase_auth: ^0.16.0
  google_sign_in: ^4.1.4
  shared_preferences: ^0.5.6+2
  fluttertoast: ^4.0.1
  cloud_firestore: ^0.13.4+1
  firebase_storage: ^3.1.3
  intl: ^0.16.1
  provider: ^4.0.4
  after_layout: ^1.0.7+2
  moor_flutter: ^2.1.1
  scoped_model: ^1.0.1
  json_annotation: ^3.0.1
  sqflite: ^1.2.2
  flutter_colorpicker: ^0.3.2
  flutter_markdown: ^0.3.4
  uuid: ^2.0.4
  bottom_navy_bar: ^5.3.2
  dynamic_theme: ^1.0.1
  image_picker: ^0.6.3+4
  flutter_datetime_picker: ^1.3.4
  cached_network_image: ^2.0.0
  firebase_core: ^0.4.4
  flutter_staggered_grid_view: ^0.3.0
  transparent_image: ^1.0.0
  flutter_sticky_header: ^0.4.2
  like_button: ^0.2.0
  #  zoomable_image: ^1.3.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.4.0
  build_runner: ^1.8.0
  json_serializable: ^3.2.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/google-48.png
    - assets/luffy.png

    # To add assets to your application, add an assets section, like this:
    # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
